from datetime import datetime
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


def utc_timestamp() -> datetime:
    """
    Return a UTC timestamp without microseconds.

    Used for consistent auditing across the
    Playwright Python Method Extraction service.
    """
    return datetime.utcnow().replace(microsecond=0)


# -----------------------------------------
# API LOG MODEL
# -----------------------------------------
class APILog(BaseModel):
    """
    Schema for storing API audit logs.

    Captures request metadata, processing metrics,
    and optional error details generated by the
    Playwright Python Method Extractor.
    """

    timestamp: datetime = Field(default_factory=utc_timestamp)

    # Request info
    method: Optional[str] = None
    path: Optional[str] = None
    query_params: Optional[Dict[str, Any]] = None
    ip: Optional[str] = None
    user_agent: Optional[str] = None

    # Processing info
    duration_ms: Optional[float] = None
    status: Optional[int] = None

    # Optional enhanced audit data
    file_name: Optional[str] = None
    method_count: Optional[int] = None
    chunk_count: Optional[int] = None

    # Error logs
    storage_error: Optional[str] = None
    error: Optional[str] = None
    traceback: Optional[str] = None

    model_config = {
        "from_attributes": False
    }


# -----------------------------------------
# RAW SCRIPT STORAGE MODEL
# -----------------------------------------
class RawScript(BaseModel):
    """
    Schema for storing uploaded Playwright Python
    scripts for auditing and debugging purposes.
    """

    filename: str
    content: str
    size: int
    timestamp: datetime = Field(default_factory=utc_timestamp)

    model_config = {
        "from_attributes": False
    }
